### ISSUE TITLE
Code returns error.....HTTPS is required, it looks like?

### ISSUE THREAD

**Issue by CT-Smyth** [witnessmenow/arduino-coinmarketcap-api#1]
I fixed the library by mashing it up with the HTTP example code lol. But I don't know (yet) how to use git, being too old school... (I actually had to look up how a pull request works, and ran out of patience for the time being when I can't edit the code right in the git window) but ill figure it out. 

there are no time outs or safeguards in this, so I suspect this could hang on a bad response.

Because I'm ignorant for the time being, I'm going to post the revision in this comment....sorry.

*******************Begin CoinMarketCapApi.h*****************
/*
Copyright (c) 2017 Brian Lough. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
*/

/*This code has been touched inappropriately by Clifford Smyth.*/

#ifndef CoinMarketCapApi_h
#define CoinMarketCapApi_h

#include <Arduino.h>
#include <ArduinoJson.h>
#include <Client.h>
#include <WiFiClientSecure.h>

#define COINMARKETCAP_HOST "api.coinmarketcap.com"

struct CMCTickerResponse{
  String id;
  String name;
  String symbol;
  int rank;
  double price_usd;
  double price_btc;
  double volume_usd_24h;
  double market_cap_usd;
  double available_supply;
  double total_supply;

  double percent_change_1h;
  double percent_change_24h;
  double percent_change_7d;
  double last_updated;

  double price_currency;
  double volume_currency_24h;
  double market_cap_currency;

  String error;
};

class CoinMarketCapApi
{
  public:
    CoinMarketCapApi (Client &client);
    String SendGetToCoinMarketCap(String command);
    CMCTickerResponse GetTickerInfo(String coinId, String currency = "");
    int COINMARKETCAP_SSL_PORT = 443;

  private:
    Client *client;
};

#endif

*******************End CoinMarketCapApi.h*****************

*******************Begin CoinMarketCapApi.cpp*****************

#include "CoinMarketCapApi.h"

CoinMarketCapApi::CoinMarketCapApi(Client &client)	{
  this->client = &client;
}

String CoinMarketCapApi::SendGetToCoinMarketCap(String command) {

  String body="";
  String headers="";
  body.reserve(700);
  bool finishedHeaders = false;
  bool currentLineIsBlank = true;
  long now;
  bool avail;

  WiFiClientSecure client;
  Serial.print("connecting to ");
  Serial.println(COINMARKETCAP_HOST);
  if (!client.connect(COINMARKETCAP_HOST, COINMARKETCAP_SSL_PORT)) {
    Serial.println("connection failed");
  }

//  Serial.print("requesting URL: ");
//  Serial.println(command);

  client.print(String("GET ") + command + 
                      " HTTP/1.1\r\n" +
                      "Host: " + COINMARKETCAP_HOST + "\r\n" +
                      "User-Agent: Arduino\r\n" +
                      "Connection: close\r\n\r\n");

//  Serial.println("request sent");
  while (client.connected()) {
    String line = client.readStringUntil('\n');
//    Serial.println("Header was:");
//    Serial.println("==========");
//    Serial.println(line);
//    Serial.println("==========");
    if (line == "\r") {
//      Serial.println("headers received");
      break;
    }
  }

  body = client.readStringUntil(']') + "]";

  
//  Serial.println("reply was:");
//  Serial.println("==========");
//  Serial.println(body);
//  Serial.println("==========");
//  Serial.println("closing connection");

  return body;
}

CMCTickerResponse CoinMarketCapApi::GetTickerInfo(String coinId, String currency) {
  // https://api.coinmarketcap.com/v1/ticker/bitcoin/
  String command="/v1/ticker/" + coinId + "/";
  if (currency != "") {
    command = command + "?convert=" + currency;
  }

  String response = SendGetToCoinMarketCap(command);

//  Serial.println("**************response****************");
//  Serial.println(response);
//  Serial.println("**************************************");

  CMCTickerResponse responseObject = CMCTickerResponse();
  DynamicJsonBuffer jsonBuffer;
	JsonArray& root = jsonBuffer.parseArray(response);
  if (root.success()) {
    responseObject.id = root[0]["id"].as<String>();
    responseObject.name = root[0]["name"].as<String>();
    responseObject.symbol = root[0]["symbol"].as<String>();
    responseObject.rank = root[0]["rank"].as<int>();
    responseObject.price_usd = root[0]["price_usd"].as<double>();

    responseObject.price_btc = root[0]["price_btc"].as<double>();
    responseObject.volume_usd_24h = root[0]["24h_volume_usd"].as<double>();
    responseObject.market_cap_usd = root[0]["market_cap_usd"].as<double>();
    responseObject.available_supply = root[0]["available_supply"].as<double>();
    responseObject.total_supply = root[0]["total_supply"].as<double>();

    responseObject.percent_change_1h = root[0]["percent_change_1h"].as<double>();
    responseObject.percent_change_24h = root[0]["percent_change_24h"].as<double>();
    responseObject.percent_change_7d = root[0]["percent_change_7d"].as<double>();
    responseObject.last_updated = root[0]["last_updated"].as<double>();

    currency.toLowerCase();
    responseObject.price_currency = root[0]["price_" + currency].as<double>();
    responseObject.volume_currency_24h = root[0]["volume_" + currency + "_24h"].as<double>();
    responseObject.market_cap_currency = root[0]["market_cap_" + currency].as<double>();
  } else {
    JsonObject& rootObject = jsonBuffer.parseObject(response);
    if (rootObject.containsKey("error")) {
       responseObject.error = rootObject["error"].as<String>();
    } else {
      responseObject.error = "Failed to parse JSON";
    }

    return responseObject;
  }
}

*******************End CoinMarketCapApi.cpp*****************

**Comment by witnessmenow** [comment]
Oh that's a pity! Let me a take a look at it later and push a fix. I was
using https before but switched to http when I saw it was supported, guess
its not anymore

**Comment by witnessmenow** [comment]
@CT-Smyth awesome that you got it working, I'll push a change with that now
