### ISSUE TITLE
Works great!

### ISSUE THREAD

**Issue by waaslandwolf** [witnessmenow/arduino-coinmarketcap-api#3]
Now this is an issue! :-)

Just wanted to drop in and let you know that I used your API code to build a little hardware ticker based on Wemos D1 ESP8266 and an LCD. Got a ticker that scrolls between multiple cryptos running in an hour or two of coding. Had zero issues with your library. Thanks for sharing your work! 

(you can close this issue :-))

John

**Comment by witnessmenow** [comment]
Haha :) 

When i seen the issue email, I was like that is a strange title for an issue.

You're welcome @waaslandwolf would love to see a photo of what you made if you wanted to share!
