### ISSUE TITLE
Trying Harder but not compiling 

### ISSUE THREAD

**Issue by Lbenza** [witnessmenow/arduino-coinmarketcap-api#5]
Hey guys, I got everything but i missing something. 

Hardware:
1 x MAX7219 4 in 1 Dot Matrix Display module
1 x ESP8266 CH340 Node MCU V3

I did no change, changes  and a lot, but nothing.
> CMCTickerResponse response = api.GetTickerInfo(ticker, "eur");

**This is my error:**   
Arduino: 1.8.5 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (1M SPIFFS)"

/Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp: In member function 'CMCTickerResponse CoinMarketCapApi::GetTickerInfo(String, String)':
/Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp:70:3: error: 'DynamicJsonBuffer' was not declared in this scope
   DynamicJsonBuffer jsonBuffer;
   ^
/Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp:70:3: note: suggested alternative:
In file included from /Users/lucho/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson/DynamicJsonDocument.hpp:10:0,
                 from /Users/lucho/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson.hpp:9,
                 from /Users/lucho/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:9,
                 from /Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.h:24,
                 from /Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp:1:
/Users/lucho/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson/Memory/DynamicJsonBuffer.hpp:159:5: note:   'ArduinoJson::Internals::DynamicJsonBuffer'
     DynamicJsonBuffer;
     ^
/Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp:70:21: error: expected ';' before 'jsonBuffer'
   DynamicJsonBuffer jsonBuffer;
                     ^
/Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp:71:20: error: 'jsonBuffer' was not declared in this scope
  JsonArray& root = jsonBuffer.parseArray(response);
                    ^
/Users/lucho/Documents/Arduino/libraries/CoinMarketCapApi/src/CoinMarketCapApi.cpp:72:12: error: 'class ArduinoJson::JsonArray' has no member named 'success'
   if (root.success()) {
            ^
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by witnessmenow** [comment]
For anyone wondering what the resolution is/was you need to install an
older version of Arduino json

**Comment by Lbenza** [comment]
thank you, the problem was that I download the wrong library, not from this GitHub.
